import sys
import unittest
from contextlib import redirect_stdout
from io import StringIO


class TestShell(unittest.TestCase):
    def test_default_encoding(self):
        self.assertEqual(sys.getdefaultencoding(), "utf-8")

    def test_filesystem_encoding(self):
        self.assertEqual(sys.getfilesystemencoding(), "utf-8")

    def test_stdout_encoding(self):
        # Case not consistent across python versions.
        self.assertEqual(sys.stdout.encoding.lower(), "utf-8")

    def test_stderr_encoding(self):
        # Case not consistent across python versions.
        self.assertEqual(sys.stderr.encoding.lower(), "utf-8")

    def test_print_utf8(self):
        s = StringIO()
        with redirect_stdout(s):
            # Generated by https://jeff.cis.cabrillo.edu/tools/homoglyphs
            print(
                b"\xf0\x9d\x91\xaf\xce\xbe\xea\x9e\x8e\xce\xb9\xc8\x8d"
                b" \xe1\xba\x80\xe0\xaf\xa6\xf0\x9d\x90\xab\xc6\x9a\xe1\xb6\x81".decode(),  # expect utf-8 default.
                end="",
            )

        self.assertEqual(s.getvalue(), "𝑯ξꞎιȍ Ẁ௦𝐫ƚᶁ")


if __name__ == "__main__":
    unittest.main()
