# {{ image_name }}
FROM {{ image_id }} AS build

ENV PACKAGES \
{% for package in packages %}
    {{ package }}{{ " \\" if not loop.last else "" }}
{% endfor %}

# - dash -
# os.system may need a shell, obviously as does subprocess with shell=True. This isn't
# very 'distroless', but is arguably no less secure since similar damage could be done
# with the python binary itself. See also,
#   https://github.com/GoogleContainerTools/distroless/issues/601
#
# - libc-bin -
# This gives us ldconfig, used to configure the runtime image, and makes
# ctypes.find_library() work.
#
# - libgcc-s1 -
# This is a dependency of libstdc++6.
#
# - ligbomp -
# A few packages expect a system install of libgomp, e.g. lightgmb,
#   https://github.com/microsoft/LightGBM/issues/4484
#
# - libstdc++6 -
# This is for manylinux2010, manylinux2014 compatibility
ENV PACKAGES_EXTRA \
    dash \
    libc-bin \
    libgcc-s1 \
    libgomp1 \
    libstdc++6

ENV PACKAGES_COPYRIGHT \
    gcc-10-base \
    libtirpc-common \
    readline-common

RUN set -eux; \
    apt-get update; \
    apt-get install -y --no-install-recommends ${PACKAGES} ${PACKAGES_COPYRIGHT} ${PACKAGES_EXTRA}; \
{% if updates|length > 0 %}
    # The updates list may include updates to packages that were present in the upgrades
    # stage only because they are debsecan dependencies. Use --only-upgrade to ignore.
    apt-get install -y --no-install-recommends --only-upgrade ${PACKAGES_UPDATE}; \
{% endif %}
    rm -rf /var/lib/apt/lists/*

# Find all the files provided by our dependency packages, and copy them to a new root
# filesystem at /tmp/rootfs.
RUN mkdir -p /tmp/rootfs
RUN set -eux; \
    echo ${PACKAGES} ${PACKAGES_EXTRA} \
    | xargs dpkg --listfiles \
    | sort --unique \
    | perl -nE 'chomp; say if -f' \
    | xargs cp --parents --archive --target-directory=/tmp/rootfs
RUN set -eux; \
    echo ${PACKAGES_COPYRIGHT} \
    | xargs dpkg --listfiles \
    | grep -i copyright \
    | perl -nE 'chomp; say if -f' \
    | xargs cp --parents --archive --target-directory=/tmp/rootfs

# Copy over the Python install. Everything in /usr/local is from Python, but we only
# want the binaries/libraries.
RUN mkdir -p /tmp/rootfs/usr/local
RUN cp --parents --archive --target-directory=/tmp/rootfs /usr/local/bin
RUN cp --parents --archive --target-directory=/tmp/rootfs /usr/local/lib

# Explicitly remove a few things that we do not expect to be required,
# and/or will not work correctly E.g. idlelib needs tk support, but
# the -slim Python images do not support tk (libtk is missing).
RUN rm -rf /tmp/rootfs/usr/local/bin/idle*; \
    rm -rf /tmp/rootfs/usr/local/bin/2to3*; \
    rm -rf /tmp/rootfs/usr/local/bin/pip*; \
    rm -rf /tmp/rootfs/usr/local/bin/wheel; \
    rm -rf /tmp/rootfs/usr/local/lib/python{{ python_version }}/ensurepip; \
    rm -rf /tmp/rootfs/usr/local/lib/python{{ python_version }}/idlelib; \
    rm -rf /tmp/rootfs/usr/local/lib/python{{ python_version }}/lib2to3; \
    rm -rf /tmp/rootfs/usr/local/lib/python{{ python_version }}/tkinter; \
    rm -rf /tmp/rootfs/usr/local/lib/python{{ python_version }}/turtle.py; \
    rm -rf /tmp/rootfs/usr/local/lib/python{{ python_version }}/turtledemo; \
    rm -rf /tmp/rootfs/usr/local/lib/python{{ python_version }}/lib-dynload/_tkinter*.so*

# The final image provides no third-party packages. Note that among
# other things, this fully removes pip: the final image is not intended
# for installation of packages.
RUN rm -rf /tmp/rootfs/usr/local/lib/python{{ python_version }}/site-packages/*


FROM gcr.io/distroless/static-debian11

ENV LANG=C.UTF-8

COPY --from=build /tmp/rootfs /

# Re-generate the ldconfig cache in the final stage to pick up the libpython in
# /usr/local/lib. The /etc/ld.so.cache from the build stage may include things
# we don't copy over.
RUN /sbin/ldconfig

ENTRYPOINT [ "python" ]
